### ISSUE TITLE
Can you share the trained model ?

### ISSUE THREAD

**Issue by wuqiangch** [wtomin/MIMA-Net#1]
@wtomin Can you share the trained model ? Thanks!

**Comment by wtomin** [comment]
Yes, I uploaded my trained models in five folds through this [URL](https://drive.google.com/file/d/1ae4Sy0WwPeTdrU6zKADCHyCrinAvrBT4/view?usp=sharing). These models are trained on Aff-wild dataset. Unfortunately, the models on the OMG dataset were accidentally deleted. I will retrain my models in the near future.

**Comment by wtomin** [comment]
The predictions are first obtained using the *_best_ccc.pth.tar on each fold. And then the 5-fold predictions are averaged to get the final predictions on test set.

**Comment by wuqiangch** [comment]
@wtomin In your trained model, the lass layer(classifier)  has two nodes. But  I dont know which one means the valence, the first or the second? Thanks!
