### ISSUE TITLE
Value Error in run_example.py

### ISSUE THREAD

**Issue by chan-kh** [wtomin/MIMA-Net#10]
Hi, @wtomin 
When I was running `run_example.py`, I have encountered a value error. The error message is the following:
```
`No CUDA devices found, falling back to CPU
No CUDA devices found, falling back to CPU
No CUDA devices found, falling back to CPU
load checkpoint from models/model_weights.pth.tar, epoch:1
output dir exists: examples/utterance_1. Video processing skipped.
output_dir examples/utterance_1_pool5 already exists, feature extraction skipped.
Traceback (most recent call last):
  File "run_example.py", line 9, in <module>
    results = tester.test(example_video)
  File "/home/ubuntu/MIMAMO-Net/api/tester.py", line 68, in test
    length=self.length, stride=self.stride)
  File "/home/ubuntu/MIMAMO-Net/api/sampler/snippet_sampler.py", line 105, in __init__
    self.parse_video()
  File "/home/ubuntu/MIMAMO-Net/api/sampler/snippet_sampler.py", line 110, in parse_video
    self.annot_dir, self.label_name, self.test_mode)
  File "/home/ubuntu/MIMAMO-Net/api/sampler/snippet_sampler.py", line 21, in __init__
    self.path_label = self.get_path_label()
  File "/home/ubuntu/MIMAMO-Net/api/sampler/snippet_sampler.py", line 27, in get_path_label
    raise ValueError("number of frames of video {} should not be zero.".format(self.video))
ValueError: number of frames of video utterance_1 should not be zero.`
```

I have no clue on fixing this bug as it seems to relate to the sample viedo. Any help or suggestion on it will be extremely helpful. Thank you.

**Comment by wtomin** [comment]
Can you check the two directories: examples/utterance_1 and examples/utterance_1_pool5, to see whether they are empty?

**Comment by chan-kh** [comment]
I am sorry for the late reply. 
`examples/utterance_1` contains `utterance_1.csv  utterance_1_aligned  utterance_1_of_details.txt` and `examples/utterance_1_pool5` is empty.

**Comment by wtomin** [comment]
Are there many cropped and aligned faces existent under `examples/utterance_1/utterance_1_aligned `?

**Comment by chan-kh** [comment]
Yes, there are a lot of bmp files ranged from `frame_det_00_000001.bmp` to `frame_det_00_000309.bmp`

**Comment by wtomin** [comment]
I think I have found where the problem is. It's possible that your previous execution created the `examples/utterance_1_pool5` but did not create the extracted features. The script found `examples/utterance_1_pool5` therefore skipped the feature extraction. That's why `examples/utterance_1_pool5` is empty.

Please delete the folder `examples/utterance_1_pool5` before you run `python run_example.py`.

**Comment by wtomin** [comment]
I will fix this problem by checking whether the output directory is empty.
